SELECT ?statement
       ?item ?name_pl ?name_en
       ?party ?party_name_pl ?party_name_en
       ?district ?district_name_pl ?district_name_en
       ?role ?role_pl ?role_en
       ?role_superclass ?role_superclass_pl ?role_superclass_en
       ?start ?end ?facebook
       ?org ?org_pl ?org_en ?org_jurisdiction ?org_seat_count
WHERE {
  BIND(wd:Q20066605 as ?role) .
  BIND(wd:Q20066605 as ?specific_role) .
  BIND(wd:Q98975 as ?org) .
  OPTIONAL {
  ?org rdfs:label ?org_pl
  FILTER(LANG(?org_pl) = "pl")
}

OPTIONAL {
  ?org rdfs:label ?org_en
  FILTER(LANG(?org_en) = "en")
}

  OPTIONAL {
    ?org wdt:P1001 ?org_jurisdiction
  }
  OPTIONAL {
    ?org wdt:P1342 ?org_seat_count
  }
  ?item wdt:P31 wd:Q5 ;
        p:P39 ?statement .
  ?statement ps:P39/wdt:P279* ?specific_role .
  OPTIONAL { ?statement pq:P580 ?start }
  OPTIONAL { ?statement pq:P582 ?end }
  
  OPTIONAL {
  ?item rdfs:label ?name_pl
  FILTER(LANG(?name_pl) = "pl")
}

OPTIONAL {
  ?item rdfs:label ?name_en
  FILTER(LANG(?name_en) = "en")
}

  OPTIONAL {
  ?role rdfs:label ?role_pl
  FILTER(LANG(?role_pl) = "pl")
}

OPTIONAL {
  ?role rdfs:label ?role_en
  FILTER(LANG(?role_en) = "en")
}

  OPTIONAL {
    ?role wdt:P279 ?role_superclass .
    ?role_superclass wdt:P279+ wd:Q4175034
    OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_pl
  FILTER(LANG(?role_superclass_pl) = "pl")
}

OPTIONAL {
  ?role_superclass rdfs:label ?role_superclass_en
  FILTER(LANG(?role_superclass_en) = "en")
}

  }
  OPTIONAL {
    ?statement pq:P768 ?district.
    OPTIONAL {
  ?district rdfs:label ?district_name_pl
  FILTER(LANG(?district_name_pl) = "pl")
}

OPTIONAL {
  ?district rdfs:label ?district_name_en
  FILTER(LANG(?district_name_en) = "en")
}

  }
  OPTIONAL {
    ?statement pq:P4100 ?party.
    OPTIONAL {
  ?party rdfs:label ?party_name_pl
  FILTER(LANG(?party_name_pl) = "pl")
}

OPTIONAL {
  ?party rdfs:label ?party_name_en
  FILTER(LANG(?party_name_en) = "en")
}

  }
  OPTIONAL { ?item wdt:P2013 ?facebook }
  BIND(COALESCE(?start, "1000-01-01T00:00:00Z"^^xsd:dateTime) AS ?start_or_sentinel)
BIND(COALESCE(?end, "9999-12-31T00:00:00Z"^^xsd:dateTime) AS ?end_or_sentinel)
FILTER (?end_or_sentinel >= "2018-01-01"^^xsd:dateTime)
FILTER (?start_or_sentinel <= "2018-12-31"^^xsd:dateTime)

} ORDER BY ?item ?role ?start ?end ?role_superclass ?party ?org ?district
